In [1]:
import numpy as np
matr1 = np.random.random((10, 3))
itog = matr1[np.arange(10), np.abs(matr1 - .5).argmin(axis=1)]
print(matr1)
print(itog)

[[0.5418263  0.85744715 0.23671222]
 [0.42215239 0.56500297 0.8587545 ]
 [0.5187421  0.33514584 0.11477526]
 [0.49893042 0.41702171 0.29514637]
 [0.40209824 0.217911   0.8863483 ]
 [0.21802207 0.52521821 0.1874587 ]
 [0.44432467 0.52179368 0.97014468]
 [0.96767654 0.37553754 0.55288556]
 [0.77802947 0.28852618 0.53362082]
 [0.8153435  0.83691994 0.75894582]]
[0.5418263  0.56500297 0.5187421  0.49893042 0.40209824 0.52521821
 0.52179368 0.55288556 0.53362082 0.75894582]


In [ ]:
matr = np.random.random((6, 6))
summa = matr.sum(axis=1)
minimal = matr.min(axis=0)
itog = summa / minimal
print(matr)
print(itog)

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
after0 = x[np.where(x[:-1] == 0)[0] + 1].max()
print(after0)

In [ ]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(x)
np.add.at(x, i, 1)
print(x)

In [ ]:
a = np.arange(16).reshape(4, 4)
size = a.shape[0]
print("N =", size)
dictionary = {i: [a[j, i - j] for j in range(i + 1) if j < size and i - j < size] 
        for i in range(size * 2 - 1)}
print(a)
print(dictionary)